### ISSUE TITLE
concurrent modification exception on waypoint creation

### ISSUE THREAD

**Issue by btwonion** [btwonion/skylper#33]
java.util.ConcurrentModificationException: null
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:1023) ~[?:?]
	at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:1046) ~[?:?]
	at dev.nyon.skylper.skyblock.mining.hollows.HollowsModule.handleWaypoints$lambda$3(HollowsModule.kt:99) ~[skylper-1.0.0-beta29-1.21.jar:?]
	at dev.nyon.skylper.extensions.event.EventHandler$invokeEvent$1.invokeSuspend(EventHandler.kt:34) ~[skylper-1.0.0-beta29-1.21.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[org_jetbrains_kotlin_kotlin-stdlib-2.0.0-e823d47a24b16be4.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.8.1-682b081a811ff4e1.jar:?]
	at dev.nyon.skylper.extensions.event.EventHandler.invokeEvent(EventHandler.kt:31) ~[skylper-1.0.0-beta29-1.21.jar:?]
	at dev.nyon.skylper.extensions.event.FabricEvents.listenForFabricEvents$lambda$0(FabricEvents.kt:8) ~[skylper-1.0.0-beta29-1.21.jar:?]
	at net.fabricmc.fabric.api.client.rendering.v1.WorldRenderEvents.lambda$static$22(WorldRenderEvents.java:223) ~[fabric-rendering-v1-5.0.5+df16efd0d1-d80ac1b079179921.jar:?]
	at net.minecraft.class_761.handler$bfd000$fabric-rendering-v1$beforeClouds(class_761.java:4289) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1255) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1087) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:850) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1285) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.0.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]

**Comment by btwonion** [comment]
https://github.com/btwonion/skylper/commit/610fdc57e5f1cb8fe7e33e8a773e272bdd920612
